---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: cnv-placement
  namespace: kubevirt
spec:
  clusterSelector:
    matchExpressions:
    - key: conf.open-cluster-management.io/cnf
      operator: Exists
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: cnv-appsub
  namespace: kubevirt
  annotations:
    apps.open-cluster-management.io/github-path: kubevirt
    apps.open-cluster-management.io/github-branch: master
spec:
  channel: ec/ec-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: cnv-placement
