apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: kubevirt-appsub
  namespace: kubevirt
spec:
  channel: ec/ec-channel
  placement:
    local: true
  packageOverrides:
  -  packageName: kubevirt
