---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: kubevirt-rule
spec:
  clusterLabels:
    matchLabels:
      team: "443"
  clusterReplicas: 1
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: kubevirt-appsub
annotations:
  apps.open-cluster-management.io/github-path: kubevirt
  apps.open-cluster-management.io/github-branch: master
spec:
  channel: ec/ec-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: kubevirt-rule
