apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: performance-addon-operator-subscription2
  namespace: openshift-performance-addon
spec:
  channel: alpha
  name: performance-addon-operator
  source: performance-addon-operator-catalogsource
  sourceNamespace: openshift-marketplace
