apiVersion: policy.mcm.ibm.com/v1alpha1
kind: Policy
metadata:
  name: policy
  namespace: kubevirt
  annotations:
    policy.mcm.ibm.com/standards: NIST
    policy.mcm.ibm.com/categories: SystemAndInformationIntegrity, RBAC
    policy.mcm.ibm.com/controls: MutationAdvisor
spec:
  remediationAction: "enforce" # enforce or inform
  complianceType: "musthave" # used as default, when missing in a particular sub-template
  namespaces:
    include: ["default"]
    exclude: ["kube*"]
  object-templates:
    - complianceType: "musthave"
      objectDefinition:
        - apiVersion: v1
          kind: Namespace
          metadata:
            labels:
              kubevirt.io: ""
            name: kubevirt
